name: Build

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Shellcheck
        uses: ludeeus/action-shellcheck@master
  docker:
    name: Docker Build
    needs:
      - shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: QEMU
        uses: docker/setup-qemu-action@v1

      - name: BuildKit
        uses: docker/setup-buildx-action@v1
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
          
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            docker.io/aw1cks/openconnect:latest
            docker.io/aw1cks/openconnect:${{ github.sha }}
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
            quay.io/aw1cks/openconnect:latest
            quay.io/aw1cks/openconnect:${{ github.sha }}
          
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
